-- EliteAuth anti-tampering migration
-- Run this once in Supabase SQL Editor before deploying worker/worker.js.

create extension if not exists pgcrypto;

alter table public.applications
  add column if not exists enforce_integrity boolean not null default false,
  add column if not exists integrity_sha256 text;

alter table public.licenses
  add column if not exists activated_at timestamptz,
  add column if not exists duration_seconds bigint;

alter table public.license_sessions
  add column if not exists challenge_hash text,
  add column if not exists integrity_sha256 text,
  add column if not exists sdk_version text,
  add column if not exists last_seen_at timestamptz;

-- Hash format constraints are added safely for existing projects.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'applications_integrity_sha256_format'
      and conrelid = 'public.applications'::regclass
  ) then
    alter table public.applications
      add constraint applications_integrity_sha256_format
      check (integrity_sha256 is null or integrity_sha256 ~ '^[a-fA-F0-9]{64}$');
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'license_sessions_integrity_sha256_format'
      and conrelid = 'public.license_sessions'::regclass
  ) then
    alter table public.license_sessions
      add constraint license_sessions_integrity_sha256_format
      check (integrity_sha256 is null or integrity_sha256 ~ '^[a-fA-F0-9]{64}$');
  end if;
end;
$$;

create table if not exists public.api_nonces (
  id bigint generated by default as identity primary key,
  application_id uuid not null references public.applications(id) on delete cascade,
  nonce text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (application_id, nonce)
);

create index if not exists api_nonces_expires_at_idx
  on public.api_nonces(expires_at);

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  application_id uuid not null references public.applications(id) on delete cascade,
  license_id uuid references public.licenses(id) on delete set null,
  event_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists security_events_application_created_idx
  on public.security_events(application_id, created_at desc);

alter table public.api_nonces enable row level security;
alter table public.security_events enable row level security;

-- Nonces are Worker-only. No browser policies are intentionally created.
revoke all on public.api_nonces from anon, authenticated;

-- Application owners can inspect security detections in the dashboard later.
drop policy if exists "Owners read own security events" on public.security_events;
create policy "Owners read own security events"
on public.security_events for select
to authenticated
using (
  exists (
    select 1
    from public.applications
    where applications.id = security_events.application_id
      and applications.owner_id = auth.uid()
  )
);

grant select on public.security_events to authenticated;

-- Atomically reserve a short-lived request nonce. Duplicate nonces are rejected.
create or replace function public.reserve_api_nonce(
  application_id_input uuid,
  nonce_input text,
  expires_at_input timestamptz
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.api_nonces
  where expires_at <= now();

  begin
    insert into public.api_nonces(application_id, nonce, expires_at)
    values (
      application_id_input,
      left(nonce_input, 128),
      greatest(expires_at_input, now() + interval '1 minute')
    );
    return true;
  exception when unique_violation then
    return false;
  end;
end;
$$;

revoke all on function public.reserve_api_nonce(uuid, text, timestamptz) from public;
grant execute on function public.reserve_api_nonce(uuid, text, timestamptz) to service_role;

-- Replace the application-creation RPC so dashboard users can configure
-- an approved SHA-256 build hash at creation time.
drop function if exists public.create_application_with_credentials(
  text,text,integer,integer,text,text,text,boolean,text
);

drop function if exists public.create_application_with_credentials(
  text,text,integer,integer,text,text,text,boolean,text,boolean,text
);

create function public.create_application_with_credentials(
  name_input text,
  prefix_input text default 'ELITE',
  groups_input integer default 4,
  chars_input integer default 4,
  separator_input text default '-',
  charset_input text default 'alphanumeric',
  case_input text default 'upper',
  exclude_ambiguous_input boolean default true,
  version_input text default '1.0.0',
  enforce_integrity_input boolean default false,
  integrity_sha256_input text default null
)
returns table (
  id uuid,
  owner_id uuid,
  app_id uuid,
  server_secret text,
  name text,
  version text,
  enforce_integrity boolean,
  integrity_sha256 text
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  generated_secret text;
  normalized_hash text;
  created_app public.applications;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  normalized_hash := lower(nullif(trim(coalesce(integrity_sha256_input, '')), ''));

  if coalesce(enforce_integrity_input, false)
     and (normalized_hash is null or normalized_hash !~ '^[a-f0-9]{64}$') then
    raise exception 'A valid 64-character SHA-256 hash is required when integrity enforcement is enabled';
  end if;

  if normalized_hash is not null and normalized_hash !~ '^[a-f0-9]{64}$' then
    raise exception 'Integrity hash must be a 64-character SHA-256 value';
  end if;

  generated_secret := encode(gen_random_bytes(24), 'hex');

  insert into public.applications (
    owner_id,
    name,
    license_prefix,
    key_groups,
    chars_per_group,
    key_separator,
    key_charset,
    key_case,
    exclude_ambiguous,
    version,
    server_secret_hash,
    enforce_integrity,
    integrity_sha256
  )
  values (
    auth.uid(),
    left(trim(name_input), 80),
    left(trim(coalesce(prefix_input, '')), 20),
    greatest(1, least(10, groups_input)),
    greatest(2, least(16, chars_input)),
    case when separator_input in ('-', '_', '.', '') then separator_input else '-' end,
    case when charset_input in ('alphanumeric', 'letters', 'numbers') then charset_input else 'alphanumeric' end,
    case when case_input in ('upper', 'lower') then case_input else 'upper' end,
    coalesce(exclude_ambiguous_input, true),
    left(coalesce(version_input, '1.0.0'), 30),
    encode(digest(generated_secret, 'sha256'), 'hex'),
    coalesce(enforce_integrity_input, false),
    normalized_hash
  )
  returning * into created_app;

  return query
  select
    created_app.id,
    created_app.owner_id,
    created_app.app_id,
    generated_secret,
    created_app.name,
    created_app.version,
    created_app.enforce_integrity,
    created_app.integrity_sha256;
end;
$$;

revoke all on function public.create_application_with_credentials(
  text,text,integer,integer,text,text,text,boolean,text,boolean,text
) from public;

grant execute on function public.create_application_with_credentials(
  text,text,integer,integer,text,text,text,boolean,text,boolean,text
) to authenticated;
